#protocols
BASIC_RIVET='BASIC_RIVET'

#shard types
WORKER='WORKER'
REFERENCE='REFERENCE'

# Event Types
#Client
EVT_SEND_TRANSACTION='SEND_TRANSACTION'

#Layer 1
EVT_RECEIVE_TRANSACTION='RECEIVE_TRANSACTION'


#layer 2
EVT_WORKER_CREATE_BLOCK='WORKER_CREATE_BLOCK'
EVT_REFERENCE_CREATE_BLOCK='REFERENCE_CREATE_BLOCK'
EVT_WORKER_VERIFY_BLOCK='WORKER_VERIFY_BLOCK'
EVT_REFERENCE_VERIFY_BLOCK='REFERENCE_VERIFY_BLOCK'